# Generated by Django 3.2 on 2021-04-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210413_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='profile_picture',
            field=models.ImageField(default='user.png', upload_to='user_images'),
        ),
    ]
